### ISSUE TITLE
Snap interface we need?

### ISSUE THREAD

**Issue by jneo8** [canonical/juju-spell#1]
This is the snapcraft.yaml which I think can cover the permission we need. Need some different point of view.

```yaml
name: juju-spell
base: core22
adopt-info: juju-spell
# version: "0.1"
summary: collects an operates at several clouds at the same time
description: |
  Connects to multiple clouds and allows to run commands at the same time.

grade: devel
confinement: devmode

apps:
  juju-spell:
    command: bin/juju-spell
    plugs:
      # For ssh-tunnel/sshuttle
      - network
      - ssh-keys
      - firewall-control
      # Access to config file
      - home
      - dot-local-share-juju-spell

parts:
  juju-spell:
    plugin: python
    python-requirements: [ ./requirements.txt ]
    source: .
    stage-packages:
      - git
    override-build: |
      snapcraftctl build
      echo "Version: $(python3 setup.py --version)"
      snapcraftctl set-version "$(python3 setup.py --version)"

plugs:
  dot-local-share-juju-spell:
    interface: personal-files
    write:
      - $HOME/.local/share/juju-spell

```
