### ISSUE TITLE
create global and local configuration options for each controller

### ISSUE THREAD

**Issue by rgildein** [canonical/juju-spell#21]
We need to add "global" part to the config and while loading the config we need to merge it with local for each controller. All logic should happen during config load.

Example defining connection timeout:

1. usage of global and local options
```yaml
connection:
  # global value
  timeout: 60
controllers:
  - ...
    connection:
      # local value for controller.0
      timeout: 30
  - ...
    connection:
     # timeout is not defined for controller.1
      ...
```
```python
assert controllers[0].connection.timeout == 30  # local value for controller.0 was loaded
assert controllers[1].connection.timeout == 60  # global value was used here
```

2. usage of default values defined in settings.py

```python
# settings.py
DEFAULT_CONNECTIN_TIMEOUT = 90  # seconds
```

```yaml
# no global configuration for connection
controllers:
 - ...
    connection:
     # timeout is not defined for controller.0
      ...
 - ...
    connection:
     # timeout is not defined for controller.1
      ...
```
```python
assert controllers[0].connection.timeout == 90  # default value was used
assert controllers[1].connection.timeout == 90  # default value was used
```

**Comment by jneo8** [comment]
I think we can have this format of configuration:


```yaml
global_controller:
  # Same format as a single controller
  ...
controllers:
  controller_a:
    ...
  controller_b:
    ...
```

And when loading config, we will first merge personal and global config files. The apply `global_key` to every element inside the list.
In this the global default config key name will be `controller` and the list of element will be `controllers`.

**Comment by esunar** [comment]
> I think we can have this format of configuration:
> 
> ```yaml
> default_controller:
>   # Same format as a single controller
>   ...
> controllers:
>   controller_a:
>     ...
>   controller_b:
>     ...
> ```
> 
> When loading config, we will follow the below steps:
> 
> 1. Apply `default_{key}` to every element inside the list if the key is not exists.

I don't thing this will be a good idea. Because it is not easy to see and understand. Also it will include lots of string processing(if startswith("default"), startswith(key) etc)

**Comment by jneo8** [comment]
Ok, but which kind of format you want to have here? I add a `different_` prefix as a mark for us to know this one is the default. Or we can do like:

```yaml
default:
  controller:
controllers:
  controller_a:
    ...
  controller_b:
    ...
```

**Comment by esunar** [comment]
I've added timeout-policy just for example. For now it can just be timeout.

```yaml
global:
  controller: 
    owner: default owner
    tags: ["default-tag"]  # optional
    risk: 5  # optional [5]
    username: default-username
    model_mapping:
      lma: monitoring
      default: production
    connection:  # optional
      timeout-policy:
        timeout-seconds: 4
        max-retry: 5
        retry-policy: lineer
        
controllers:
  - name: example_controller
    customer: example_customer
    owner: Gandalf
    description: some nice notes about controllers and models  # optional
    tags: ["test"]  # optional
    risk: 5  # optional [5]
    endpoint: 10.1.1.46:17070
    ca_cert: |
        -----BEGIN CERTIFICATE-----
        -----END CERTIFICATE-----
    username: admin
    password: pass1234
    model_mapping:
      lma: monitoring
      default: production
    connection:  # optional
      timeout-policy:
        timeout-seconds: 4
        max-retry: 5
        retry-policy: lineer    
      destination: ubuntu@10.1.1.99  # infra node
      subnets:  # optional (sshuttle)
        - 10.1.1.0/24
        - 20.1.1.0/24
      jumps:  # optional
        - bastion
```

**Comment by rgildein** [comment]
I agree w/ @esunar, there is no need for any prefixes in my opinion even
```yaml
global:
  controller: 
```
is not needed, but I can understand that using keys directly can be confusing. e.g.
```
owner: default owner  # this is default value
...
controllers:
- name: ...
```
What about `global: ` without controller? Since every configuration is related with single controller we can easily skip `controller` key.

Here's how I think we should implement it:
- load yaml file
- pop `global` configuration
- iterate over controllers and add configuration from global if key does not exists
- validate updated config (without global key)
- create object Config

**Comment by jneo8** [comment]
> I agree w/ @esunar, there is no need for any prefixes in my opinion even
> 
> ```yaml
> global:
>   controller: 
> ```
> 
> is not needed, but I can understand that using keys directly can be confusing. e.g.
> 
> ```
> owner: default owner  # this is default value
> ...
> controllers:
> - name: ...
> ```
> 
> What about `global: ` without controller? Since every configuration is related with single controller we can easily skip `controller` key.
> 
> Here's how I think we should implement it:
> 
> * load yaml file
> * pop `global` configuration
> * iterate over controllers and add configuration from global if key does not exists
> * validate updated config (without global key)
> * create object Config

I think the `default` or `global` like below is needed.

```yaml
default:
  controller:
    ...
controllers:
  controller_a:
    ...
  controller_b:
    ...
```

I think first we both agree with the key(default or global, but I will try to avoid using global here, because we already have config/personal configs. Default will be more simple to understand.)

Second, I think we need to have *controller* key, which maps to *controllers*, in default. Because it's about scalability. I don't want to change the format in the future.
