### ISSUE TITLE
Retry policy

### ISSUE THREAD

**Issue by jneo8** [canonical/juju-spell#63]
We want to add a retry-policy option on the configuration.

```yaml
controllers:
  controller-a:
    retry-policy:
      timeout: 5
```

Here are some requirement need to clear:

1. Is retry-policy works on **connect to controller** ?
2. Is retry-policy works on **build ssh tunnel/ssuttle** ?

Here is the issues:

1. Right now we don't have retry policy in code to build *ssh connection*, only retry on **build connection to controller**.

2. The connection section in controller config right now only represent the options to build the ssh connection, which may confuse people because we after implementation we will have *controller.endpoint*, *controller.connection*, and *controller.retry-policy*. I think maybe it's OK to have, but we need a detailed document.

Here is the options we can take:

1. Add a retry-policy config option in section of config *controller.retry-policy*, which only work for building connection to juju controller.

2. Add a retry-policy config option in section of config *controller.retry-policy*, which works for juju controller's connection and ssh connection.

3. Add a retry-policy config option in both section of config *controller.retry-policy* and *controller.connection.retry-policy*, which should affect ssh connection and controller connection.

**Comment by esunar** [comment]
All ssh options can be configured by .ssh/config thus only controller connection is enough.

**Comment by jneo8** [comment]
So the section to put config is OK for you?

```yaml
controllers:
  controller-a:
    retry-policy:
      timeout: 5
    connection:
      ...
```
